# Generated by Django 5.1 on 2024-09-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumption',
            name='energy_price',
            field=models.FloatField(default=0.12),
        ),
        migrations.AddField(
            model_name='energyconsumption',
            name='renewable_efficiency',
            field=models.FloatField(default=0.8),
        ),
    ]
