# Generated by Django 5.1 on 2024-09-10 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_energyconsumption_energy_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumption',
            name='renewable_source',
        ),
        migrations.AddField(
            model_name='energyconsumption',
            name='sunlight_hours',
            field=models.FloatField(default=5.0, help_text='Average hours of sunlight per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
