# Generated by Django 5.1 on 2024-09-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_remove_energyconsumption_renewable_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumption',
            name='number_of_appliances',
        ),
    ]
